django/account/urls.py
from django.urls import include, path

from account.views import CreateUser, Login, logout_view

app_name = 'account'

urlpatterns = [
    path('register/', CreateUser.as_view(), name='register'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

django/api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('get_parent_categroy/<int:category_id>',
         views.CategoryList.as_view()
         )
]

django/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mercari.urls')),
    path('api/', include('api.urls')),
    path('account/', include('account.urls'), name='account'),
]

django/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!-- css -->
    <link
            href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            rel="stylesheet"
            integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
            integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
            integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
            crossorigin="anonymous"
    />
    <link rel="stylesheet" href="../static/mercari.css"/>
    <!-- script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"
    ></script>
    <title>Rakus Items</title>
</head>
<body>
<!-- navbar -->
{% if user.is_authenticated %}
    <nav class="navbar navbar-inverse">
        <div class="navbar-header">
            <button
                    type="button"
                    class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#navbar"
                    aria-expanded="false"
                    aria-controls="navbar"
            >
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'list' %}">Rakus Items</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <div>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a id="logout" href="{% url 'account:logout' %}"
                        >Logout&nbsp;<i class="fa fa-power-off"></i
                        ></a>
                    </li>
                </ul>
                <p class="navbar-text navbar-right">
                    <span id="loginName">user: {{ user.get_username }}</span>
                </p>
            </div>
        </div>
    </nav>
{% else %}
    <!-- not login  -->
    <nav class="navbar navbar-inverse">
        <a class="navbar-brand" href="{% url 'list' %}">Rakus Items</a>
    </nav>
{% endif %}

{% block content %}
{% endblock %}
</body>
</html>

django/templates/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="input-main" class="container">
        <a type="button" class="btn btn-default" href="{% url 'list' %}"
        ><i class="fa fa-reply"></i> back</a
        >
        <h2>Edit</h2>

        <!-- edit form -->
        <form action="#" method="POST" class="form-horizontal">
            {% if error %}
                <div class="alert alert-dark" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <!-- name -->
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
    <script type="text/javascript" src="{% static 'js/category.js' %}"></script>
{% endblock %}

django/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- details -->
    <div class="container">
        <a type="button" class="btn btn-default" href="{% url 'list' %}"
        ><i class="fa fa-reply"></i> back</a
        >
        <h2>Details</h2>
        <div id="details">
            <table class="table table-hover">
                <tbody>
                <tr>
                    <th>ID</th>
                    <td>{{ item.item_id }}</td>
                </tr>
                <tr>
                    <th>name</th>
                    <td>{{ item.name }}</td>
                </tr>
                <tr>
                    <th>price</th>
                    <td>{{ item.price }}</td>
                </tr>
                <tr>
                    <th>category</th>
                    <td>
                        {% if item.category %}
                            <span>{{ item.category.parent.parent.descendant.name }}</span>
                            /
                            <span>{{ item.category.parent.descendant.name }}</span>
                            /
                            <span>{{ item.category.descendant.name }}</span>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>brand</th>
                    <td>{{ item.brand }}</td>
                </tr>
                <tr>
                    <th>condition</th>
                    <td>{{ item.condition }}</td>
                </tr>
                <tr>
                    <th>description</th>
                    <td>{{ item.description }}</td>
                </tr>
                </tbody>
            </table>
            <a type="button" class="btn btn-default" href="{% url 'edit' item.item_id %}"
            ><i class="fa fa-pencil-square-o"></i>&nbsp;edit</a
            >
        </div>
    </div>
{% endblock %}

django/templates/edit.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <!-- details -->
    <div id="input-main" class="container">
        <a type="button" class="btn btn-default" href="{% url 'detail' pk %}"
        ><i class="fa fa-reply"></i> back</a>
        <h2>EDIT</h2>
        <!-- edit form -->
        <form action="#" method="POST" class="form-horizontal">
            {% if error %}
                <div class="alert alert-dark" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <!-- name -->
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </div>
    <script type="text/javascript" src="{% static 'js/category.js' %}"></script>

{% endblock %}

django/templates/list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div id="main" class="container-fluid">
        <!-- addItem link -->
        <div id="addItemButton">
            <a class="btn btn-default" href="{% url 'create' %}"
            ><i class="fa fa-plus-square-o"></i> Add New Item</a
            >
        </div>

        <!-- 検索フォーム -->
        <div id="forms">
            <form action="" class="form-inline" role="form" method="GET">
                {{ form.as_p }}
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-angle-double-right"></i> search
                </button>
            </form>
        </div>

        <!-- pagination -->
        {% include 'pagination.html' %}

        <!-- table -->
        <div class="table-responsive">
            <table id="item-table" class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th>name</th>
                    <th>price</th>
                    <th>category</th>
                    <th>brand</th>
                    <th>cond</th>
                </tr>
                </thead>
                <tbody>
                {% for item in item_list %}
                    <tr>
                        <td class="item-name">
                            <a href="{% url 'detail' item.item_id %}">{{ item.name }}</a>
                        </td>
                        <td class="item-price">{{ item.price }}</td>
                        <td class="item-category">
                            {% if item.category %}
                                <a
                                        href="?category={{ item.category.parent.parent.descendant.category_id }}"
                                >{{ item.category.parent.parent.descendant.name }}</a
                                >
                                /
                                <a
                                        href="?category={{ item.category.parent.descendant.category_id }}"
                                >{{ item.category.parent.descendant.name }}</a
                                >
                                /
                                <a href="?category={{ item.category.descendant.category_id }}"
                                >{{ item.category.descendant.name }}</a
                                >
                            {% endif %}
                        </td>
                        <td class="item-brand"><a href="?test=&brand={{ item.brand }}">{{ item.brand }}</a></td>
                        <td class="item-condition">{{ item.condition }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <!-- pagination -->
        {% include 'pagination.html' %}

        <!-- ページ番号を指定して表示するフォーム -->
        <div id="select-page">
            <form class="form-inline" action='' method="GET">
                <div class="form-group">
                    <div class="input-group col-xs-6">
                        <label></label>
                        <input
                                type="text"
                                class="form-control"
                                name="page"
                                value="{{ page_obj.number }}"
                        />
                        {% if form.data.category %}
                            <input
                                    type="hidden"
                                    name="category"
                                    value="{{ form.data.category }}"
                            />
                        {% endif %}
                        {% if form.data.name %}
                            <input
                                    type="hidden"
                                    name="name"
                                    value="{{ form.name.value }}"
                            />
                        {% endif %}
                        {% if form.data.brand %}
                            <input
                                    type="hidden"
                                    name="brand"
                                    value="{{ form.brand.value }}"
                            />
                        {% endif %}
                        <!-- 総ページ数 -->
                        <div class="input-group-addon">
                            {{ page_obj.paginator.num_pages }}
                        </div>
                    </div>
                    <div class="input-group col-xs-1">
                        <button type="submit" class="btn btn-default">Go</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/category.js' %}"></script>
{% endblock %}

django/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <!-- login form -->
    <div id="login" class="container">
        <div class="panel panel-default">
            <div class="panel-heading">Login</div>
            <div class="panel-body">
                {% if form.errors %}
                    <p>ユーザーID, パスワードが一致しません．</p>
                {% endif %}
                <form method="POST">
                    {% csrf_token %}
                    <label>ユーザーID</label>
                    {{ form.username }}
                    {{ form.username.errors }}
                    <label>パスワード</label>
                    {{ form.password }}
                    {{ form.password.errors }}
                    <button type="submit" class="btn btn-primary">ログイン</button>
                </form>
            </div>
        </div>
        <div>
            <a type="button" class="btn btn-default" href="{% url 'account:register' %}"><i class="fa fa-user-plus"></i>&nbsp;Register
                Account</a>
        </div>
    </div>
{% endblock %}

django/templates/pagination.html
<div class="pages">
    <nav class="page-nav">
        <div class="pager">
            <div class="col-lg-6">
                {% if page_obj.has_previous %}
                    <form action='' method="GET" class="text-left form-inline">
                        <label></label>
                        <input
                                type="hidden"
                                class="form-control"
                                name="page"
                                value="{{ page_obj.previous_page_number }}"
                        />
                        {% if form.data.category %}
                            <input
                                    type="hidden"
                                    name="category"
                                    value="{{ form.data.category }}"
                            />
                        {% endif %}
                        {% if form.data.name %}
                            <input
                                    type="hidden"
                                    name="name"
                                    value="{{ form.name.value }}"
                            />
                        {% endif %}
                        {% if form.data.brand %}
                            <input
                                    type="hidden"
                                    name="brand"
                                    value="{{ form.brand.value }}"
                            />
                        {% endif %}
                        <!-- 総ページ数 -->
                        <button
                                type="submit"
                                class="btn btn-primary text-right">&larr; prev
                        </button>
                    </form>
                {% endif %}
            </div>
            <div class="col-lg-6">
                {% if page_obj.has_next %}
                    <form action='' method="GET" class="text-right form-inline">
                        <label></label>
                        <input
                                type="hidden"
                                class="form-control"
                                name="page"
                                value="{{ page_obj.next_page_number }}"
                        />
                        {% if form.data.category %}
                            <input
                                    type="hidden"
                                    name="category"
                                    value="{{ form.data.category }}"
                            />
                        {% endif %}
                        {% if form.data.name %}
                            <input
                                    type="hidden"
                                    name="name"
                                    value="{{ form.name.value }}"
                            />
                        {% endif %}
                        {% if form.data.brand %}
                            <input
                                    type="hidden"
                                    name="brand"
                                    value="{{ form.brand.value }}"
                            />
                        {% endif %}
                        <!-- 総ページ数 -->
                        <button
                                type="submit"
                                class="btn btn-primary text-right">next &rarr;
                        </button>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>
</div>

django/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- register form -->
    <div id="login" class="container">
        <div class="panel panel-default">
            <div class="panel-heading">Register Account</div>
            <div class="panel-body">
                <form method="POST">
                    {% csrf_token %}
                    <label>ユーザーID</label>
                    {{ form.username }}
                    {{ form.username.errors }}
                    <label>パスワード</label>
                    {{ form.password1 }}
                    {{ form.password1.errors }}
                    <label>パスワード(確認)</label>
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                    <button type="submit">登録</button>
                </form>
            </div>
        </div>
        <div>
            <a type="button" class="btn btn-default" href="login.html"><i class="fa fa-reply"></i>&nbsp;Login page</a>
        </div>
    </div>
{% endblock %}